# pip install Appium-Python-Client

import time
from appium import webdriver

caps = {}
caps["platformName"] = "ANDROID"
caps["platformVersion"] = "6.0.1"
caps["deviceName"] = "Pixel_3a"
caps["UDID"] = "emulator-5554"
caps["autoWebview"] = False
caps['autoGrantPermissions'] = True
caps["appActivity"] = "com.lenddo.mobile.paylater.home.activity.SplashScreenActivity"
caps["appPackage"] = "com.lenddo.mobile.paylater.staging"

driver = webdriver.Remote("http://localhost:4723/wd/hub", caps)

element1 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/carbonUpButton")
element1.click()
time.sleep(10)
element2 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/tutorial_skip")
element2.click()
time.sleep(10)
element3 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/user_type_existing")
element3.click()
element4 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/sign_in_phone")
element4.send_keys("08990001099")
element5 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/sign_in_pin")
element5.send_keys("1234")
element6 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/sign_in_next")
element6.click()
time.sleep(10)
element7 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/tvRightNow")
element7.click()


element8 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.support.v4.widget.DrawerLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout[3]/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.TextView")
element8.click()
time.sleep(10)
element9 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/edit_text_phone_number")
element9.send_keys("08100067519")
time.sleep(10)
element10 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/edit_text_airtime_price")
element10.send_keys("1000")
time.sleep(10)
element11 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.support.v4.widget.DrawerLayout/android.widget.LinearLayout/android.widget.Button")
element11.click()
time.sleep(10)
element12 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/walletRadioButton")
element12.click()
time.sleep(10)
element13 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/button_confirm_payment")
element13.click()
time.sleep(10)
element20 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/button_pay")
element20.click()
time.sleep(10)
element14 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[1]")
element14.send_keys('1')
element15 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[2]")
element15.send_keys('2')
element16 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[3]")
element16.send_keys('3')
element17 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[4]")
element17.send_keys('4')
element18 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/success_home_button")
element18.click()
element19 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/okayButton")
element19.click()
element20 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/fundWalletButton")
element20.click()
element21 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/fundWalletCard")
element21.click()
element22 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/walletAmountToFund")
element22.send_keys("1000")
element23 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/proceedWalletFunding")
element23.click()
element24 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/image_check")
element24.click()
element25 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/button_confirm_payment")
element25.click()
element26 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/secure_pay_button")
element26.click()
element27 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/edit_pin_placeholder1")
element27.send_keys('1')
element28 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[2]")
element28.send_keys('2')
element29 = driver.find_element_by_xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout[3]")
element29.send_keys('3')
element30 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/edit_pin_placeholder4")
element30.send_keys('4')
element31 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/success_home_button")
element31.click()
element32 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/okayButton")
element32.click()
element33 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/viewWalletTransactionsButton")
element33.click()
element34 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/title_menu_item_others")
element34.click()
element35 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/createdAtEditText")
element35.click()
element36 = driver.find_element_by_id("android:id/button1")
element36.click()
element37 = driver.find_element_by_id("com.lenddo.mobile.paylater.staging:id/endAtEditText")
element37.click()
element38 = driver.find_element_by_id("android:id/button1")
element38.click()

driver.quit()